[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.1.0"

[dependencies]
bitflags = "0.8.2"
fnv = "1.0.5"
isbn = "0.1.0"
lazy_static = "0.2.8"
libc = "0.2.22"
png = "0.7.0"
regex = "0.2.2"
reqwest = "0.7.2"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
titlecase = "0.10.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"
