[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.6.4"
edition = "2018"

[[bin]]
name = "plato"
path = "src/main.rs"

[[bin]]
name = "plato-import"
path = "src/importer.rs"
required-features = ["importer"]

[[bin]]
name = "plato-emulator"
path = "src/emulator.rs"
required-features = ["emulator"]

[dependencies]
bitflags = "1.0.4"
downcast-rs = "1.0.3"
failure = "0.1.3"
failure_derive = "0.1.3"
fnv = "1.0.6"
isbn = "0.1.0"
lazy_static = "1.2.0"
libc = "0.2.45"
png = "0.13.2"
regex = "1.1.0"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
titlecase = "0.10.0"
unicode-normalization = "0.1.7"
glob = "0.2.11"
rand = "0.6.1"
crockford = "1.0.1"
toml = "0.4.10"
zip = { version = "0.5.0", features = ["deflate"], default-features = false }
hyphenation = "0.7.1"
entities = "1.0.1"
paragraph-breaker = "0.4.2"
rand_xorshift = "0.1.0"
xi-unicode = "0.1.0"

[dependencies.getopts]
version = "0.2.18"
optional = true

[dependencies.reqwest]
version = "0.9.5"
optional = true

[dependencies.chrono]
features = ["serde"]
version = "0.4.6"

[dependencies.sdl2]
version = "0.32.0"
optional = true

[features]
importer = ["reqwest", "getopts"]
emulator = ["sdl2"]
