[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.3.0"

[[bin]]
name = "plato"
path = "src/main.rs"

[[bin]]
name = "plato-import"
path = "src/importer.rs"
required-features = ["importer"]

[dependencies]
bitflags = "1.0.1"
downcast-rs = "1.0.0"
error-chain = "0.11.0"
fnv = "1.0.6"
isbn = "0.1.0"
lazy_static = "1.0.0"
libc = "0.2.34"
png = "0.11.0"
regex = "0.2.5"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
titlecase = "0.10.0"
unicode-normalization = "0.1.5"

[dependencies.html-entities]
version = "0.1.0"
optional = true

[dependencies.getopts]
version = "0.2.15"
optional = true

[dependencies.reqwest]
version = "0.8.2"
optional = true

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"
[profile.release]
panic = "abort"

[features]
importer = ["reqwest", "getopts", "html-entities"]
