[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.2.1"

[[bin]]
name = "plato"
path = "src/main.rs"

[[bin]]
name = "plato-import"
path = "src/importer.rs"

[dependencies]
bitflags = "1.0.1"
downcast-rs = "1.0.0"
error-chain = "0.11.0"
fnv = "1.0.6"
getopts = "0.2.15"
html-entities = "0.1.0"
isbn = "0.1.0"
lazy_static = "1.0.0"
libc = "0.2.34"
png = "0.11.0"
regex = "0.2.3"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
titlecase = "0.10.0"
unicode-normalization = "0.1.5"

[dependencies.reqwest]
version = "0.8.1"
optional = true

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"
[profile.release]
panic = "abort"
