[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.1.0"

[dependencies]
bitflags = "1.0.0"
downcast-rs = "1.0.0"
error-chain = "0.11.0"
fnv = "1.0.5"
isbn = "0.1.0"
lazy_static = "0.2.8"
libc = "0.2.30"
png = "0.9.0"
regex = "0.2.2"
reqwest = "0.7.3"
serde = "1.0.14"
serde_derive = "1.0.14"
serde_json = "1.0.3"
titlecase = "0.10.0"
unicode-normalization = "0.1.5"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"
