[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.7.9"
edition = "2018"

[[bin]]
name = "plato"
path = "src/main.rs"

[[bin]]
name = "plato-import"
path = "src/importer.rs"
required-features = ["importer"]

[[bin]]
name = "plato-emulator"
path = "src/emulator.rs"
required-features = ["emulator"]

[[bin]]
name = "article_fetcher"
path = "src/fetcher.rs"
required-features = ["fetcher"]

[dependencies]
bitflags = "1.2.1"
downcast-rs = "1.1.0"
failure = "0.1.6"
failure_derive = "0.1.6"
fnv = "1.0.6"
lazy_static = "1.4.0"
libc = "0.2.65"
png = "0.15.0"
regex = "1.3.1"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
titlecase = "0.10.0"
unicode-normalization = "0.1.8"
glob = "0.3.0"
rand = "0.7.2"
crockford = "1.0.1"
toml = "0.5.3"
zip = "0.5.3"
kl-hyphenate = "0.7.2"
entities = "1.0.1"
paragraph-breaker = "0.4.3"
rand_xorshift = "0.2.0"
xi-unicode = "0.2.0"
septem = "1.0.1"
byteorder = "1.3.2"
flate2 = "1.0.12"
levenshtein = "1.0.4"

[dependencies.getopts]
version = "0.2.21"
optional = true

[dependencies.reqwest]
version = "0.9.22"
features = ["rustls-tls"]
default-features = false
optional = true

[dependencies.chrono]
features = ["serde"]
version = "0.4.9"

[dependencies.sdl2]
version = "0.32.2"
optional = true

[dependencies.crossbeam-channel]
version = "0.3.9"
optional = true

[dependencies.signal-hook]
version = "0.1.10"
optional = true

[features]
importer = ["getopts"]
emulator = ["sdl2"]
fetcher = ["reqwest", "crossbeam-channel", "signal-hook"]
