[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "font"
version = "0.1.0"

[lib]
name = "font"
path = "lib.rs"

[dependencies]
libc = "0.2.34"
bitflags = "1.0.1"
error-chain = "0.11.0"
geom = { path = "../geom" }
framebuffer = { path = "../framebuffer" }
