[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "framebuffer"
version = "0.1.0"

[lib]
name = "framebuffer"
path = "lib.rs"

[dependencies]
png = "0.11.0"
libc = "0.2.34"
error-chain = "0.11.0"
geom = { path = "../geom" }
color = { path = "../color" }
